### ISSUE TITLE
Laravel Pint

### ISSUE THREAD

**Issue by bradyrenting** [protonemedia/laravel-guidelines#2]
Hi! 👋

The opinionated PHP code style fixer [Laravel Pint](https://github.com/laravel/pint) has been released just a couple of days ago.

It's straightforward, simple to use and in my opinion a great addition when working in teams.

I have compared the PHP CS Fixer config you already implemented and the default Laravel Pint config and noticed there aren't _that_ many differences. If you like, I'm willing to create a `pint.json` config with all the missing options based on your config.

Would like to hear your suggestions and/or thoughts on implementing this 😄

**Comment by pascalbaljet** [comment]
I agree! The two most important differences for me are the `binary_operator_spaces` and `not_operator_with_successor_space` settings.

**Comment by bradyrenting** [comment]
Cool! Here's a [PR](https://github.com/protonemedia/laravel-guidelines/pull/3) including the Pint config, does this look ok to you? Anything missing?

Also, does this mean PHP CS Fixer will be completely replaced by Pint? If so, I can change it and push it to this PR.
